@echo off
echo Starting Projector Manager...
echo.
echo Step 1: Starting Vite server...
start /b cmd /c "npm run dev"
echo Waiting 5 seconds for Vite to start...
timeout /t 5 /nobreak
echo.
echo Step 2: Starting Electron...
set NODE_ENV=development
electron src-electron/main.js
pause